### ISSUE TITLE
Golang draw and  how to set text bold？

### ISSUE THREAD

**Issue by AndrewXiGua** [penhauer-xiao/browser#1]
hi，I saw you closed the issue by https://github.com/golang/freetype/issues/64#issue-352815941
Did you has solved the problem?

**Comment by wpecker** [comment]
@lishaoh  Yes,  I had solved

**Comment by AndrewXiGua** [comment]
> @lishaoh Yes, I had solved

@penhauer-xiao Did you use bold.ttf? or other ways

**Comment by wpecker** [comment]
@lishaoh  Yes
